# Membuat objek service untuk projek producer dan menghubungkannya berdasarkan selector serta mengatur port servicenya ke 3001
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-producer-service
spec:
  type: NodePort
  selector:
    app: rabbitmq-producer
  ports:
    - port: 3000