apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
  labels:
    app: karsajobs-ui
    tier: app
spec:
# Create only one replica pod
  replicas: 1
  selector:
    matchLabels:
      tier: app
  template: 
    metadata: 
      labels:
        app: karsajobs-ui
        tier: app
    spec:
      containers:
      - name: webapp
      # Pull image from github package
        image: ghcr.io/naufalazmi48/karsajobs-ui:latest
        ports: 
        # Set container port 
          - containerPort: 8000