# Membuat objek service untuk projek consumer dan menghubungkannya berdasarkan selector serta mengatur port servicenya ke 3001
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq-consumer
  name: rabbitmq-consumer-service
spec:
  type: NodePort
  selector:
    app: rabbitmq-consumer
  ports:
    - port: 3001