version: 2.1

jobs:
  lint-dockerfile:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: docker container run --rm -i hadolint/hadolint hadolint - < Dockerfile
  test-app:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    machine: 
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: sh "docker/scripts/build_push_image_karsajobs.sh"

workflows:
  lint_test_build_and_push:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs